import { Client } from "pg";
import "dotenv/config";

const sql = `CREATE TABLE IF NOT EXISTS shippable_trucks (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
truck_id VARCHAR (20),
org_code VARCHAR (4)
);

CREATE TABLE IF NOT EXISTS orders (
order_number BIGINT PRIMARY KEY,
customer VARCHAR
);

CREATE TABLE IF NOT EXISTS items (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
part_number VARCHAR,
description VARCHAR,
part_mark VARCHAR
);

CREATE TABLE IF NOT EXISTS users (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR,
last_name VARCHAR,
plant VARCHAR
);

CREATE TABLE IF NOT EXISTS order_items (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
part_id INT references items(id),
order_number BIGINT references orders(order_number),
quantity INT 
);

CREATE TABLE IF NOT EXISTS packages (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
package_name VARCHAR,
order_number BIGINT references orders(order_number),
status TEXT
);

CREATE TABLE IF NOT EXISTS containers (
id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
package_id INT references packages(id),
order_number BIGINT references orders(order_number),
container_name VARCHAR
);

INSERT INTO shippable_trucks (id, truck_id, org_code)
VALUES
('1','2600429001T1', 'ANN'),
('2','PRIJ1500918948L6', 'STJ');

INSERT INTO orders (order_number, customer)
VALUES
('2600429001', 'BLUESCOPE'),
('25022626301', 'HEARTLAND CONSTRUCTION, INC');

INSERT INTO items (id, part_number, description, part_mark)
VALUES
('1','55307', '1/4-14 X 1 1/4" Carbon (TEKS 3)', 'N/A'),
('2','0025390', 'PANLASTIC W/CUBE 1/4 X 40', 'N/A'),
('3','GFB2050*6987859', 'FG-FLANGE-BRACE', 'GFB2050');

INSERT INTO users (id, first_name, last_name, plant)
VALUES
('1', 'Anthony', 'Vauthier', 'ANN'), ('2', 'Charles', 'Demokowski', 'STJ');

INSERT INTO order_items (part_id, order_number, quantity)
VALUES
('1', '2600429001', '20'),
('2', '2600429001', '1'),
('1', '25022626301', '30');

INSERT INTO packages (id, package_name, order_number, status)
VALUES
('1','1AT', '2600429001', 'Staged/Pick Confirmed'),
('2','1ABT1', '2600429001', 'Staged/Pick Confirmed'),
('3','1AT1', '25022626301', 'Staged/Pick Confirmed'),
('4','30M', '25022626301', 'Staged/Pick Confirmed');

INSERT INTO containers (package_id, order_number, container_name)
VALUES
('1', '2600429001', 'GJYF'),
('2', '2600429001', 'GJYF'),
('3', '25022626301', 'BB884'),
('4', '25022626301', 'BB884');

ALTER TABLE shippable_trucks ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE users ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE order_items ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE packages ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE containers ALTER COLUMN id SET GENERATED ALWAYS;
`;

async function main() {
  const client = new Client({
    connectionString: process.env.DB_STRING,
  });
  try {
    console.log("connecting...");
    await client.connect();
    console.log("connected. seeding...");
    const res = await client.query(sql);
    console.log("res", res);
    console.log("done");
  } catch (err) {
    console.log(err);
  } finally {
    await client.end();
  }
}

main();

/*
CREATE TABLE IF NOT EXISTS containers (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
package_id INT references packages(id),
order_number INT references orders(order_number)
container_name VARCHAR,
);

INSERT INTO containers (container_name, package_name, order_number)
VALUES
('GJYF', '1AT', '2600429001'),
('GJYF', '1ABT1', '2600429001'),
('BB884', '1AT1', '25022626301'),
('BB884', '30M', '25022626301');
*/
